function result = singlePhaseTg(localSegment,min_fit_length)
%SINGLEPHASETG Summary of this function goes here
%   Detailed explanation goes here
    result = struct('solidStateBaseline',[],...
        'startOfTg',[],...
        'endOfTg',[],...
        'semiSolidBaseline',[],...
        'liquidStateBaseline',[],...
        'tanhBaseline',[],...
        'fictiveTemp',[],...
        'deltaCp',[],...
        'meltTemp',[],...
        'heatOfFusionTotal',[],...
        'heatOfFusionFirstContact',[],...
        'heatOfFusionSecondary',[],...
        'orgIndex',[]);

    solid_state_SOD = fitsStartOfDataTg(localSegment,min_fit_length);
    [best_solid_state_fit,rubbery_state_start] = endOfSSPoint(min_fit_length,solid_state_SOD);
    result.solidStateBaseline = best_solid_state_fit.bestFitParam;
    result.startOfTg = localSegment(best_solid_state_fit.length,1);
    result.endOfTg = localSegment(rubbery_state_start,1);
    best_rubbery_state = rubberyStateBaselineTg(localSegment,rubbery_state_start,min_fit_length);
    solid_state_end = result.startOfTg;
    rubbery_state_start = result.endOfTg;
    best_solid_state = best_solid_state_fit.baseline;
    [fictive_temp,deltaCp] = fictiveTemp(localSegment,solid_state_end,...
        rubbery_state_start,best_solid_state,best_rubbery_state);
    result.fictiveTemp = fictive_temp;
    result.deltaCp = deltaCp;
end

